DROP TABLE IF EXISTS RESERVATION;
DROP TABLE IF EXISTS TENANT;
DROP TABLE IF EXISTS RENTER;
DROP TABLE IF EXISTS ITEM_LEASED;

CREATE TABLE TENANT (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE RENTER (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE ITEM_LEASED (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    unit_cost DOUBLE NOT NULL,
    area DOUBLE NOT NULL,
    description VARCHAR (2000)
);

CREATE TABLE RESERVATION (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    cost DOUBLE NOT NULL
--     renter_id BIGINT FOREIGN KEY REFERENCES renter(id),
-- renter_id BIGINT FOREIGN KEY REFERENCES tenant(id),
--     item_leased_id BIGINT FOREIGN KEY REFERENCES item_leased(id),
--     lease_start DATE NOT NULL
--     lease_end DATE NOT NULL
);

ALTER TABLE RESERVATION
    ADD CONSTRAINT reservation_tenant_id
    FOREIGN KEY (tenant_id) REFERENCES tenant(id)
